import StyleDictionary from 'style-dictionary'

/**
 * Custom format: emit a nested JS object that mirrors the token tree.
 *
 * Style Dictionary's built-in `javascript/es6` format produces flat
 * constants (`ColorPrimaryBg = '#3B82F6'`) — great for code, but Tailwind's
 * theme object needs nested groups (colors.button.bg.primary). This format
 * walks the resolved token tree and rebuilds it as a nested object, with
 * numeric scale keys preserved as strings.
 */
StyleDictionary.registerFormat({
  name: 'javascript/tailwind-tokens',
  format: async ({ dictionary }) => {
    const tree = {}
    for (const token of dictionary.allTokens) {
      let node = tree
      for (let i = 0; i < token.path.length - 1; i++) {
        const key = token.path[i]
        node[key] = node[key] ?? {}
        node = node[key]
      }
      node[token.path[token.path.length - 1]] = token.$value ?? token.value
    }
    return `// AUTO-GENERATED by Style Dictionary. Do not edit.\n` +
           `// Source: design-tokens/tokens/**\n` +
           `export default ${JSON.stringify(tree, null, 2)}\n`
  },
})

export default {
  // DTCG format uses $value / $type — tell SD to parse it.
  usesDtcg: true,

  // Read every JSON file under tokens/ as a token source.
  // Order doesn't matter; SD builds a single merged dictionary.
  source: ['design-tokens/tokens/**/*.json'],

  // Global log level — 'warn' flags unresolved references loudly.
  log: { verbosity: 'verbose' },

  platforms: {
    /**
     * 1. CSS custom properties — consumed at runtime via a stylesheet import.
     *    Each token becomes `--button-bg-primary: #3B82F6;` on :root.
     *    `outputReferences: true` preserves var() chains so semantic tokens
     *    reference core tokens in the output (enables runtime theme swaps).
     */
    css: {
      transformGroup: 'css',
      buildPath: 'design-tokens/build/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },

    /**
     * 2. Tailwind-consumable JS — imported by tailwind.config.js at build time.
     *    Emits a nested object matching the token tree so you can cherry-pick
     *    groups into Tailwind's theme.extend (see tailwind.config.js).
     */
    tailwind: {
      // 'js' transformGroup strips units from dimensions for JS consumers.
      // We DON'T want that for Tailwind (it needs '16px' not 16), so use a
      // custom array of transforms instead.
      transforms: ['attribute/cti', 'name/kebab', 'color/css'],
      buildPath: 'design-tokens/build/tailwind/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/tailwind-tokens',
        },
      ],
    },

    /**
     * 3. Flat JSON — useful for docs, Storybook, or shipping to other teams.
     */
    json: {
      transformGroup: 'js',
      buildPath: 'design-tokens/build/json/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/flat',
        },
      ],
    },
  },
}
